# Generated by Django 2.1 on 2019-09-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Event Name')),
                ('description', models.TextField(blank=True)),
                ('price', models.FloatField(max_length=3)),
                ('recommendation_level', models.IntegerField(blank=True, null=True)),
                ('in_stock', models.BooleanField()),
            ],
        ),
    ]
